steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'testero-frontend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=3000'
      - '--set-env-vars=NODE_ENV=production,NEXT_PUBLIC_SITE_URL=https://testero.ai'

# Store images in Google Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA'

# Set timeout to 30 minutes
timeout: 1800s
