steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_SITE_URL=https://testero.ai',
      # Note: For production Cloud Build, configure these as substitution variables:
      # '--build-arg', 'NEXT_PUBLIC_POSTHOG_KEY=${_POSTHOG_KEY}',
      # '--build-arg', 'NEXT_PUBLIC_POSTHOG_HOST=${_POSTHOG_HOST}', 
      # '--build-arg', 'NEXT_PUBLIC_SUPABASE_URL=${_SUPABASE_URL}',
      # '--build-arg', 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'testero-frontend'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--port=3000'
      - '--set-env-vars=NODE_ENV=production'

# Store images in Google Artifact Registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/testero/frontend:$COMMIT_SHA'

# Set timeout to 30 minutes
timeout: 1800s
