import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { POST } from "@/app/api/billing/webhook/route";
import { grantPmlePass, refundPmlePass } from "@/lib/stripe/pmle-pass";
import { trackPurchaseCompleted } from "@/lib/analytics/server";
const m = vi.hoisted(() => ({ construct: vi.fn(), session: vi.fn(), subscription: vi.fn(), ctor: vi.fn(), db: {} as unknown, calls: [] as { table: string; operation: string; value?: unknown; filters: unknown[] }[], results: {} as Record<string, unknown[]> }));
vi.mock("@/lib/stripe/stripe-service", () => ({ StripeService: class { constructor() { m.ctor(); } constructWebhookEvent = m.construct; retrieveCheckoutSession = m.session; retrieveSubscription = m.subscription; } }));
vi.mock("@/lib/supabase/service", () => ({ createServiceSupabaseClient: () => m.db }));
vi.mock("@/lib/stripe/pmle-pass", async original => ({ ...await original<typeof import("@/lib/stripe/pmle-pass")>(), grantPmlePass: vi.fn(), refundPmlePass: vi.fn() }));
vi.mock("@/lib/analytics/server", () => ({ trackPurchaseCompleted: vi.fn() }));
const ownedSession = { id: "cs_test_owned", mode: "payment", payment_status: "paid", metadata: { user_id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa", plan_name: "PMLE Pass" }, payment_intent: "pi_owned", customer: "cus_owned", line_items: { has_more: false, data: [{ price: { id: "price_pass" }, quantity: 1 }] }, amount_total: 3900, currency: "usd" };
const checkoutEvent = { id: "evt_checkout", type: "checkout.session.completed", created: 1_791_000_000, data: { object: { id: "cs_test_owned" } } };
function req(signature: string | null = "signed_mock", body = "raw-body") { return new Request("http://localhost:3000/api/billing/webhook", { method: "POST", headers: signature ? { "stripe-signature": signature } : {}, body }); }
function result(table: string, op: string, value: unknown) { (m.results[`${table}:${op}`] ??= []).push(value); }
function makeDb() {
  return { rpc(name: string, args: unknown) {
    m.calls.push({ table: "rpc", operation: name, value: args, filters: [] });
    return Promise.resolve(m.results[`rpc:${name}`]?.shift() ?? { data: null, error: null });
  }, from(table: string) {
    let operation = "select"; let value: unknown; const filters: unknown[] = [];
    const builder = {
      select() { operation = "select"; return builder; }, insert(input: unknown) { operation = "insert"; value = input; return builder; }, update(input: unknown) { operation = "update"; value = input; return builder; }, upsert(input: unknown) { operation = "upsert"; value = input; return builder; },
      eq(column: string, input: unknown) { filters.push([column, input]); return builder; },
      maybeSingle() { return Promise.resolve(finish()); },
      then(resolve: (value: unknown) => unknown) { return Promise.resolve(finish()).then(resolve); },
    };
    function finish() { m.calls.push({ table, operation, value, filters }); return m.results[`${table}:${operation}`]?.shift() ?? { data: null, error: null }; }
    return builder;
  } };
}
beforeEach(() => { vi.stubEnv("STRIPE_PRICE_PMLE_PASS", "price_pass"); vi.stubEnv("STRIPE_WEBHOOK_SECRET", "whsec_mock"); m.calls = []; m.results = {}; m.db = makeDb(); m.construct.mockReset().mockReturnValue(checkoutEvent); m.session.mockReset().mockResolvedValue(ownedSession); vi.mocked(grantPmlePass).mockReset().mockResolvedValue({ pass: {} as never, refunded: false }); vi.mocked(refundPmlePass).mockReset().mockResolvedValue(undefined); vi.mocked(trackPurchaseCompleted).mockReset().mockResolvedValue(undefined); });
afterEach(() => vi.unstubAllEnvs());
describe("signed replay-safe billing webhook", () => {
  it("requires raw SDK signature verification before all DB access", async () => { const missing = await POST(req(null)); expect(missing.status).toBe(400); expect(m.calls).toEqual([]); expect(m.ctor).not.toHaveBeenCalled(); m.construct.mockImplementation(() => { throw new Error("private raw error"); }); const invalid = await POST(req("bad", "{raw}")); expect(invalid.status).toBe(400); expect(await invalid.json()).toEqual({ error: "Invalid webhook signature" }); expect(m.construct).toHaveBeenCalledWith("{raw}", "bad", "whsec_mock"); expect(m.calls).toEqual([]); expect(invalid.headers.get("cache-control")).toBe("private, no-store"); });
  it("retrieves full checkout, grants by reviewed port, records writes before processed", async () => { const r = await POST(req()); expect(r.status).toBe(200); expect(m.session).toHaveBeenCalledWith("cs_test_owned"); expect(grantPmlePass).toHaveBeenCalledWith(expect.anything(), m.db, ownedSession); expect(m.calls.map(c => `${c.table}:${c.operation}`)).toEqual(["webhook_events:select", "webhook_events:insert", "rpc:record_pmle_pass_payment", "webhook_events:update"]); expect(m.calls.at(-1)?.value).toMatchObject({ processed: true, error: null }); expect(m.calls.find(c => c.table === "rpc")?.value).toEqual({ p_stripe_payment_intent_id: "pi_owned", p_amount: 3900, p_currency: "usd" }); expect(m.calls.some(c => c.table === "payment_history")).toBe(false); expect(trackPurchaseCompleted).toHaveBeenCalledWith("cs_test_owned"); expect(r.headers.get("cache-control")).toBe("private, no-store"); });
  it("skips duplicate processed events before Stripe reads or new grants", async () => { result("webhook_events", "select", { data: { processed: true }, error: null }); expect((await POST(req())).status).toBe(200); expect(grantPmlePass).not.toHaveBeenCalled(); expect(m.session).not.toHaveBeenCalled(); expect(trackPurchaseCompleted).not.toHaveBeenCalled(); expect(m.calls).toHaveLength(1); });
  it("replays unprocessed event safely without reinserting the ledger", async () => { result("webhook_events", "select", { data: { processed: false }, error: null }); expect((await POST(req())).status).toBe(200); expect(grantPmlePass).toHaveBeenCalledOnce(); expect(m.calls.some(c => c.operation === "insert")).toBe(false); });
  it("allows duplicate ledger insert race but still fulfills through idempotent RPC", async () => { result("webhook_events", "insert", { error: { code: "23505" } }); expect((await POST(req())).status).toBe(200); expect(grantPmlePass).toHaveBeenCalledOnce(); });
  it.each([ { mode: "subscription" }, { payment_status: "unpaid" }, { metadata: { user_id: "victim", plan_name: "Other" } }, { line_items: { has_more: false, data: [{ price: { id: "price_other" }, quantity: 1 }] } } ])("does not grant nonpass/unpaid/other-price checkout %#", async change => { m.session.mockResolvedValue({ ...ownedSession, ...change }); expect((await POST(req())).status).toBe(200); expect(grantPmlePass).not.toHaveBeenCalled(); expect(trackPurchaseCompleted).not.toHaveBeenCalled(); expect(m.calls.some(c => c.table === "payment_history" || c.table === "rpc")).toBe(false); });
  it("rejects mismatched Stripe checkout identity", async () => { vi.spyOn(console, "error").mockImplementation(() => {}); m.session.mockResolvedValue({ ...ownedSession, id: "cs_wrong" }); expect((await POST(req())).status).toBe(503); expect(grantPmlePass).not.toHaveBeenCalled(); expect(m.calls.some(c => (c.value as { processed?: boolean })?.processed)).toBe(false); });
  it.each(["lookup", "insert", "grant", "history", "processed"])("keeps event unprocessed on durable failure: %s", async stage => { vi.spyOn(console, "error").mockImplementation(() => {}); const error = { message: "secret SDK/customer/email" }; if (stage === "lookup") result("webhook_events", "select", { data: null, error }); if (stage === "insert") result("webhook_events", "insert", { error }); if (stage === "grant") vi.mocked(grantPmlePass).mockRejectedValueOnce(error); if (stage === "history") result("rpc", "record_pmle_pass_payment", { error }); if (stage === "processed") result("webhook_events", "update", { error }); const r = await POST(req()); expect(r.status).toBe(503); expect(JSON.stringify(await r.json())).not.toContain("secret"); expect(trackPurchaseCompleted).not.toHaveBeenCalled(); expect(JSON.stringify(m.calls)).not.toContain("secret"); if (stage !== "processed") expect(m.calls.some(c => (c.value as { processed?: boolean })?.processed)).toBe(false); });
  it("refund-before-checkout and partial refunds always use durable refund RPC", async () => { m.construct.mockReturnValue({ id: "evt_refund", type: "charge.refunded", created: 1_791_000_000, data: { object: { id: "ch_owned", payment_intent: "pi_owned", refunded: false, amount_refunded: 1 } } }); expect((await POST(req())).status).toBe(200); expect(refundPmlePass).toHaveBeenCalledWith(m.db, "pi_owned", new Date(1_791_000_000 * 1000).toISOString()); expect(grantPmlePass).not.toHaveBeenCalled(); expect(trackPurchaseCompleted).not.toHaveBeenCalled(); expect(m.calls.some(c => c.table === "payment_history")).toBe(false); });
  it("a refund DB failure is retryable and never marks event processed", async () => { vi.spyOn(console, "error").mockImplementation(() => {}); m.construct.mockReturnValue({ id: "evt_refund", type: "charge.refunded", created: 1_791_000_000, data: { object: { payment_intent: "pi_owned" } } }); vi.mocked(refundPmlePass).mockRejectedValue(new Error("failed")); expect((await POST(req())).status).toBe(503); expect(m.calls.some(c => (c.value as { processed?: boolean })?.processed)).toBe(false); });
  it("suppresses purchase analytics for already-refunded checkout fulfillment", async () => { vi.mocked(grantPmlePass).mockResolvedValue({ pass: {} as never, refunded: true }); expect((await POST(req())).status).toBe(200); expect(m.calls.find(c => c.table === "rpc")?.value).toEqual({ p_stripe_payment_intent_id: "pi_owned", p_amount: 3900, p_currency: "usd" }); expect(m.calls.some(c => c.table === "payment_history")).toBe(false); expect(trackPurchaseCompleted).not.toHaveBeenCalled(); });
  it("ignores succeeded intents/subscription-created rather than granting new tiers", async () => { m.construct.mockReturnValue({ id: "evt_ignored", type: "customer.subscription.created", data: { object: {} } }); expect((await POST(req())).status).toBe(200); expect(grantPmlePass).not.toHaveBeenCalled(); expect(m.subscription).not.toHaveBeenCalled(); expect(m.calls.some(c => c.table === "user_subscriptions")).toBe(false); });
  it("refreshes only an existing owned legacy subscription, not stale event status", async () => { m.construct.mockReturnValue({ id: "evt_legacy", type: "customer.subscription.updated", data: { object: { id: "sub_legacy", status: "active" } } }); result("user_subscriptions", "select", { data: { id: "row_legacy", stripe_customer_id: "cus_legacy" }, error: null }); m.subscription.mockResolvedValue({ id: "sub_legacy", customer: "cus_legacy", status: "canceled", cancel_at_period_end: false }); expect((await POST(req())).status).toBe(200); const update = m.calls.find(c => c.table === "user_subscriptions" && c.operation === "update"); expect(update?.value).toMatchObject({ status: "canceled" }); expect(update?.filters).toContainEqual(["id", "row_legacy"]); expect(m.subscription).toHaveBeenCalledWith("sub_legacy"); });
});
