/**
 * PMLE Domain Mapping: Legacy → Blueprint
 * 
 * Maps legacy topic-based domain codes to canonical blueprint domain codes.
 * See docs/pmle-domain-mapping.md for mapping rationale.
 */

/**
 * Mapping from legacy domain codes to canonical blueprint domain codes
 */
export const LEGACY_TO_BLUEPRINT_MAP: Record<string, string> = {
  // ARCHITECTING_LOW_CODE_ML_SOLUTIONS
  AUTOML_FOR_TABULAR_TEXT_AND_IMAGE_DATA: 'ARCHITECTING_LOW_CODE_ML_SOLUTIONS',
  BIGQUERY_ML_FOR_CLASSIFICATION_AND_REGRESSION: 'ARCHITECTING_LOW_CODE_ML_SOLUTIONS',
  ML_APIS_AND_MODEL_GARDEN_APPLICATIONS: 'ARCHITECTING_LOW_CODE_ML_SOLUTIONS',
  RETRIEVAL_AUGMENTED_GENERATION_RAG_WITH_VERTEX_AI_AGENT_BUILDER: 'ARCHITECTING_LOW_CODE_ML_SOLUTIONS',
  
  // COLLABORATING_TO_MANAGE_DATA_AND_MODELS
  VERTEX_AI_FEATURE_STORE_MANAGEMENT: 'COLLABORATING_TO_MANAGE_DATA_AND_MODELS',
  ML_METADATA_TRACKING_AND_LINEAGE: 'COLLABORATING_TO_MANAGE_DATA_AND_MODELS',
  MODEL_VERSIONING_AND_AB_TESTING: 'COLLABORATING_TO_MANAGE_DATA_AND_MODELS',
  VERTEX_AI_WORKBENCH_AND_JUPYTER_ENVIRONMENTS: 'COLLABORATING_TO_MANAGE_DATA_AND_MODELS',
  
  // SCALING_PROTOTYPES_INTO_ML_MODELS
  CUSTOM_TRAINING_WITH_DIFFERENT_ML_FRAMEWORKS: 'SCALING_PROTOTYPES_INTO_ML_MODELS',
  DISTRIBUTED_TRAINING_WITH_TPUS_AND_GPUS: 'SCALING_PROTOTYPES_INTO_ML_MODELS',
  HYPERPARAMETER_TUNING_STRATEGIES: 'SCALING_PROTOTYPES_INTO_ML_MODELS',
  ML_EXPERIMENTS_TRACKING_WITH_VERTEX_AI_EXPERIMENTS: 'SCALING_PROTOTYPES_INTO_ML_MODELS',
  FINE_TUNING_FOUNDATIONAL_MODELS: 'SCALING_PROTOTYPES_INTO_ML_MODELS',
  
  // SERVING_AND_SCALING_MODELS
  ONLINE_AND_BATCH_PREDICTION_DEPLOYMENT: 'SERVING_AND_SCALING_MODELS',
  SCALING_SERVING_INFRASTRUCTURE_AND_HARDWARE_SELECTION: 'SERVING_AND_SCALING_MODELS',
  MODEL_OPTIMIZATION_FOR_PRODUCTION: 'SERVING_AND_SCALING_MODELS',
  
  // AUTOMATING_AND_ORCHESTRATING_ML_PIPELINES
  VERTEX_AI_PIPELINES_AND_KUBEFLOW_ORCHESTRATION: 'AUTOMATING_AND_ORCHESTRATING_ML_PIPELINES',
  DATA_PREPROCESSING_WITH_DATAFLOW_AND_TFX: 'AUTOMATING_AND_ORCHESTRATING_ML_PIPELINES',
  AUTOMATED_MODEL_RETRAINING_STRATEGIES: 'AUTOMATING_AND_ORCHESTRATING_ML_PIPELINES',
  CICD_FOR_ML_WITH_CLOUD_BUILD: 'AUTOMATING_AND_ORCHESTRATING_ML_PIPELINES',
  
  // MONITORING_ML_SOLUTIONS
  MODEL_MONITORING_AND_DRIFT_DETECTION: 'MONITORING_ML_SOLUTIONS',
  EXPLAINABLE_AI_AND_MODEL_INTERPRETABILITY: 'MONITORING_ML_SOLUTIONS',
  RESPONSIBLE_AI_AND_BIAS_DETECTION: 'MONITORING_ML_SOLUTIONS',
};

/**
 * Map a legacy domain code to a blueprint domain code
 * 
 * @param legacyCode - Legacy domain code (e.g., "BIGQUERY_ML_FOR_CLASSIFICATION_AND_REGRESSION")
 * @returns Blueprint domain code, or null if no mapping exists
 */
export function mapLegacyDomainToBlueprint(legacyCode: string): string | null {
  return LEGACY_TO_BLUEPRINT_MAP[legacyCode] || null;
}

/**
 * Get all legacy domain codes that map to a specific blueprint domain
 * 
 * @param blueprintCode - Blueprint domain code
 * @returns Array of legacy domain codes that map to this blueprint domain
 */
export function getLegacyDomainsForBlueprint(blueprintCode: string): string[] {
  return Object.entries(LEGACY_TO_BLUEPRINT_MAP)
    .filter(([, target]) => target === blueprintCode)
    .map(([legacy]) => legacy);
}

