name: Storybook CI

on:
  pull_request:
    branches:
      - "**"

jobs:
  storybook-build:
    name: Build Storybook (PR)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package manager
        id: pm
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "manager=pnpm" >> "$GITHUB_OUTPUT"
            echo "lock=pnpm-lock.yaml" >> "$GITHUB_OUTPUT"
          elif [ -f package-lock.json ]; then
            echo "manager=npm" >> "$GITHUB_OUTPUT"
            echo "lock=package-lock.json" >> "$GITHUB_OUTPUT"
          else
            echo "manager=npm" >> "$GITHUB_OUTPUT"
            echo "lock=package-lock.json" >> "$GITHUB_OUTPUT"
          fi

      - name: Detect Node version file
        id: node-version
        run: |
          if [ -f .nvmrc ]; then
            echo "use-file=true" >> "$GITHUB_OUTPUT"
          else
            echo "use-file=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Node (nvmrc)
        if: ${{ steps.node-version.outputs.use-file == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: ${{ steps.pm.outputs.manager }}
          cache-dependency-path: ${{ steps.pm.outputs.lock }}

      - name: Setup Node
        if: ${{ steps.node-version.outputs.use-file != 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: ${{ steps.pm.outputs.manager }}
          cache-dependency-path: ${{ steps.pm.outputs.lock }}

      - name: Install dependencies
        run: |
          if [ "${{ steps.pm.outputs.manager }}" = "pnpm" ]; then
            corepack enable
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      - name: Verify Storybook presence
        run: |
          if [ "${{ steps.pm.outputs.manager }}" = "pnpm" ]; then
            pnpm storybook:verify
          else
            npm run storybook:verify
          fi

      - name: Build Storybook
        run: |
          if [ "${{ steps.pm.outputs.manager }}" = "pnpm" ]; then
            pnpm storybook:build
          else
            npm run storybook:build
          fi

      - name: Upload Storybook artifact
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: storybook-static
          if-no-files-found: error
          retention-days: 7
